"""msg

Revision ID: 90069490d3c3
Revises: 78b477499a87
Create Date: 2024-02-22 17:33:33.302667

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '90069490d3c3'
down_revision: Union[str, None] = '78b477499a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lat_lng', 'points', ['lat', 'lng'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lat_lng', 'points', type_='unique')
    # ### end Alembic commands ###
